services:
  db:
    image: postgres:16-alpine
    container_name: nutrigym_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: nutrigym
      POSTGRES_PASSWORD: nutrigym
      POSTGRES_DB: nutrigym
    ports:
      - "5432:5432"
    volumes:
      - nutrigym_pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nutrigym_frontend
    restart: unless-stopped 
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://nutrigym:nutrigym@db:5432/nutrigym
    ports: 
      - "3000:3000"
volumes:
  nutrigym_pgdata:
